services:
    frontend:
        image: node:20
        working_dir: /app
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - '5173:5173' # For local development!
        command: >
            sh -c "npm i && npm run start"

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - /home/ubuntu/nginx/ssl:/etc/nginx/ssl # Монтируем сертификаты
        ports:
            - '80:80'
            - '443:443'
        depends_on:
            - frontend
        extra_hosts:
            - 'host.docker.internal:host-gateway'
