services:
    frontend:
        image: node:20
        working_dir: /app
        volumes:
            - ./:/app
            - /app/node_modules
        command: >
            sh -c "npm i && npm run build"

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/:/etc/nginx/
        ports:
            - '80:80'
            - '443:443'
        depends_on:
            - frontend
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        command: >
            sh -c "chmod +x /etc/nginx/generate-certs.sh && sh /etc/nginx/generate-certs.sh"
