# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    push:
        branches: ['better-deploy', 'dev']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm i
            - run: npm run build
            - run: npm test --if-present

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install SSH Client
              run: sudo apt-get update && sudo apt-get install -y openssh-client

            - name: chmod
              uses: appleboy/ssh-action@master
              with:
                  host: 37.139.41.110
                  username: ubuntu
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: ssh ubuntu@37.139.41.110 "mkdir -p /home/ubuntu/frontend/"

            # - name: Create remote directory (if it doesn't exist)
            #   run: ssh ubuntu@37.139.41.110 "mkdir -p /home/ubuntu/frontend/"

            - name: Copy build artifacts via SSH
              run: rsync -avzP ./dist/ ubuntu@37.139.41.110:/home/ubuntu/frontend/
